language: java

jdk:
  - oraclejdk8

os:
  - linux

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper

script:
  - ./gradlew clean build --info

script:
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then ./gradlew bintrayUpload --info; fi
